### ISSUE TITLE
onErr unexplained behaviour

### ISSUE THREAD

**Issue by jofomah** [redgeoff/pouchdb-persist#4]
Firstly, i must say i find this lib very useful.

i have the following option object:

```Javascript
   var options = {
        url: remoteUrl, // remote Couch URL
        maxTimeout: 60000, // max retry timeout, defaulted to 300000
        startingTimeout: 1000, // retry timeout, defaulted to 1000
        backoff: 1.1, // exponential backoff factor, defaulted to 1.1
        manual: false, // when true, start replication with start()
        changes: { // options for changes()
          opts: {
            live: true
          }
        },
        // options for replicating to remote source
        to: {
          // replicate.to() options
          opts: {
            live: true
          },
          url: remoteUrl,
          onErr: function (err) {
            //error alert here
          },
          listeners: [{
            method: 'once',
            event: 'uptodate',
            listener: function () {
             //alert here
            }
          }]
        }
      }

```

also pass filter design doc name as part of options.from.opts.filter = 'filterName', on fresh install (the database is clean) i.e the design doc does not exist locally, onErr gets triggered and throws the following error:

> error: truemessage: "missing"name: "not_found"reason: "missing"result: Object status: 404

i think this means the filter design doc does not exist, but i call replication.start() only after the replication of design docs has been completed.

You opinion on what might be the cause will be really helpful.

**Comment by redgeoff** [comment]
On the surface, it looks like you are setting `manual` to false, which means that `replication.start()` is called automatically. If you want to ensure that the replication doesn't start until you call `replication.start()` then use `manual: true`

**Comment by jofomah** [comment]
Thanks, that must be it, i misread `manual: false, // when true, start replication with start()`

**Comment by jofomah** [comment]
So that fixed it, am gonna close this. Thanks
