### ISSUE TITLE
Demo isn't work.

### ISSUE THREAD

**Issue by cesarve77** [redgeoff/pouchdb-persist#5]

**Comment by uoziod** [comment]
oh, really?

**Comment by yduartep** [comment]
Using the version pouchdb-6.4.3 the function persist is never found. I get the error: 
- db.persist is not a function

**Comment by redgeoff** [comment]
You should use the live replication features in pouchdb and not pouchdb-persist: https://github.com/redgeoff/pouchdb-persist/blob/master/README.md#status-do-not-use-pouchdb-persist-as-it-will-not-work-with-the-latest-pouchdb-pouchdb-persist-was-created-when-there-were-no-similar-options-in-pouchdb-instead-use-the-live-replication-settings-in-pouchdb
